document.writeln("<!DOCTYPE html >");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=UTF-8\'>");
document.writeln("    <meta content=\'width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no\' id=\'viewport\'");
document.writeln("          name=\'viewport\'>");
document.writeln("    <meta content=\'telephone=no\' name=\'format-detection\'>");
document.writeln("    <meta http-equiv=\'Cache-Control\' content=\'no-siteapp\'>");
document.writeln("    <meta http-equiv=\'Cache-Control\' content=\'no-transform\'>");
document.writeln("    <meta name=\'referrer\' content=\'never\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'static/images/favicon.ico\'>");
document.writeln("    <link rel=\'bookmark\' type=\'image/x-icon\' href=\'static/images/favicon.ico\'>");
document.writeln("    <title> MK剧吧丨天天影站丨最新电影丨最新韩剧丨最新美剧丨最新泰剧丨最新日剧丨东京食尸鬼百度云资源，网盘资源在线观看</title>");
document.writeln("    <style type=\'text/css\'>");
document.writeln("        * {");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<iframe src=\'http://www.mkjuba.com\' frameborder=\'no\' border=\'0\' marginwidth=\'0\' marginheight=\'0\' allowtransparency=\'yes\'");
document.writeln("        style=\'position:absolute;top:0;left:0;right:0;bottom:0;z-index:999;height:100%; width:100%;background-color:#FFF;\'></iframe>");
document.writeln("");
document.writeln("<div style=\'display:none;\'>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
